### ISSUE TITLE
Show number of connected peers 

### ISSUE THREAD

**Issue by evilrobot-01** [paritytech/trappist-extra#12]

**Comment by Daanvdplas** [comment]
[System_peers](https://github.com/smol-dot/smoldot/blob/main/light-base/src/sync_service.rs#L241): Returns the list of peers from the [`network_service::NetworkService`] that are used to synchronize blocks. Returns, for each peer, their identity and best block number and hash.

**Comment by evilrobot-01** [comment]
> [System_peers](https://github.com/smol-dot/smoldot/blob/main/light-base/src/sync_service.rs#L241): Returns the list of peers from the [`network_service::NetworkService`] that are used to synchronize blocks. Returns, for each peer, their identity and best block number and hash.

Unfortunately that method doesnt seem to be publicly available to using `system_health` RPC as per Substract Connect for now.
